# Generated by Django 5.2.7 on 2025-10-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_region",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="偏好地区"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_region_values",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="偏好地区值"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_specialty",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="偏好专科"
            ),
        ),
    ]
