# Generated by Django 5.2.7 on 2025-10-25 10:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="摘要"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="payload"
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, default=list, null=True, verbose_name="result"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "推荐历史",
                "verbose_name_plural": "推荐历史",
                "db_table": "accounts_recommendationhistory",
                "ordering": ["-created_at"],
            },
        ),
    ]
