# Generated by Django 5.2.7 on 2025-10-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_user_preferred_region_user_preferred_region_values_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="preferred_specialty",
        ),
    ]
