# Generated by Django 5.2.7 on 2025-10-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_preferred_specialty"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="history",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="历史记录"
            ),
        ),
    ]
