# Generated by Django 5.2.7 on 2025-10-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("region", models.CharField(max_length=100)),
                ("specialty", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("contact", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
