# Generated by Django 5.2.7 on 2025-10-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="医院名称"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="例如：省/市/区",
                        max_length=150,
                        verbose_name="地区",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        help_text="逗号分隔多个专科",
                        max_length=300,
                        verbose_name="专科/擅长",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="详细地址"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="联系方式"
                    ),
                ),
                (
                    "grade_level",
                    models.IntegerField(
                        choices=[
                            (3, "三级甲等 (3)"),
                            (2, "二级甲等 (2)"),
                            (1, "一级 (1)"),
                            (0, "其他 (0)"),
                        ],
                        db_index=True,
                        default=0,
                        help_text="数值：3=三甲, 2=二级甲等, 1=一级, 0=其他",
                        verbose_name="医院等级",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        help_text="WGS84，经度",
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        help_text="WGS84，纬度",
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "avg_cost",
                    models.FloatField(
                        blank=True,
                        help_text="货币单位的平均诊疗费用（用于与用户经济承受比较）",
                        null=True,
                        verbose_name="平均诊疗费用",
                    ),
                ),
                (
                    "bed_count",
                    models.IntegerField(blank=True, null=True, verbose_name="床位数"),
                ),
                (
                    "specialty_score",
                    models.FloatField(
                        default=50.0,
                        help_text="0-100 标度",
                        verbose_name="专科能力评分",
                    ),
                ),
                (
                    "equipment_score",
                    models.FloatField(
                        default=50.0,
                        help_text="0-100 标度",
                        verbose_name="设备水平评分",
                    ),
                ),
                (
                    "reputation_index",
                    models.FloatField(
                        default=50.0,
                        help_text="0-100 标度",
                        verbose_name="社会声誉指数",
                    ),
                ),
                (
                    "success_rate",
                    models.FloatField(
                        default=0.8, help_text="0-1 标度", verbose_name="治疗成功率"
                    ),
                ),
                (
                    "avg_wait_hours",
                    models.FloatField(
                        blank=True, null=True, verbose_name="平均候诊时间(小时)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "医院",
                "verbose_name_plural": "医院",
                "ordering": ("-grade_level", "name"),
                "indexes": [
                    models.Index(
                        fields=["region"], name="hospital_ho_region_804964_idx"
                    ),
                    models.Index(
                        fields=["grade_level"], name="hospital_ho_grade_l_574ba1_idx"
                    ),
                ],
            },
        ),
    ]
